name: Dev Build (Single Source, .NET Framework 4.8)

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read RimWorld game version
        id: game_version  
        run: |
          $version = Get-Content game_version.txt
          echo "GAME_VERSION=$version" >> $env:GITHUB_ENV
      - name: Install NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore Source/CrimsonGridFramework.sln
        
      - name: Set up MSBuild for .NET Framework
        uses: microsoft/setup-msbuild@v2

      - name: Build mod DLL
        run: |
          msbuild Source/CrimsonGridFramework.csproj /p:Configuration=Release /p:TargetFrameworkVersion=v4.8
      
      - name: Prepare artifact folder
        run: |
          mkdir artifact
          robocopy . artifact /E /XD Source .git .github obj bin artifact .gitignore
          exit 0

      - name: Zip artifact
        run: |
          Compress-Archive -Path artifact\* -DestinationPath CrimsonGrid-Framework-${{ env.GAME_VERSION }}.zip

      - name: Upload dev artifact
        uses: actions/upload-artifact@v4
        with:
          name: CrimsonGrid-Framework-${{ env.GAME_VERSION }}
          path: CrimsonGrid-Framework-${{ env.GAME_VERSION }}.zip
          
      - name: Comment artifact link on PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🔗 [Download DLL artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
      
            The compiled DLL can be downloaded for testing from this run.
